// Generated by typings
// Source: shared_types/koa-logger-winston.d.ts
declare module 'koa-logger-winston' {
import * as Koa from 'koa';

var koaLoggerWinston: koaLoggerWinston.KoaLoggerWinston;
export = koaLoggerWinston;

namespace koaLoggerWinston {

  interface KoaLoggerWinston {
    (winstonInstance: any): any;
  }
}
}
